[project]
name = "ai-proj"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = "==3.11.*"
dependencies = [
    "numpy<2.0",
    "onnxruntime<1.18",
    "opencv-python<4.10",
    "torch==2.2.2",
    "ultralytics>=8.4.33",
]

[tool.uv]
environments = ["sys_platform == 'darwin'"]
